spring.application.name=skyvisa
# NEON BULUT VERİTABANI AYARLARI
spring.datasource.url=jdbc:postgresql://ep-orange-water-aqf7y6dr.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nO9Cxq8hrSyQ

# Tabloları bulutta otomatik oluşturması için
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Render.com için zorunlu dinamik port ayarı
server.port=${PORT:8080}